### PR TITLE
Add React test app

### PR DESCRIPTION
**Pull request by Altai-man**

### CODE REVIEW

**Review by jnthn — COMMENTED** [review]
This would be fine in the `test-js` repository, but for this one we need TypeScript.

**Comment by jnthn** [comment]
(Probably you can just put exactly this as a PR for the JS repo and then typescript-ify this one.)

**Comment by Altai-man** [comment]
Ah, sorry. That was dumb, I sort of assumed it'll be typescript out of the box. D'oh.

**Review by jnthn — APPROVED** [review]
Will do for what we need; arguably `index.js` could be `index.ts` too.

**Pull request merged**
